import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import ReactLenis from "lenis/react";
// import ReactLenis from "lenis/react";
import 'react-phone-number-input/style.css';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactLenis root>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased            h-full w-full `}
        >
           {/* <div className="bg-violet-400 absolute top-[61px] min-h w-full h-auto z-50">1111111111111</div> */}
          {children}
          <ToastContainer />
        </body>
      </ReactLenis>
    </html>
  );
}
